server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:curiokeep}
    username: ${DB_USER:curiokeep}
    password: ${DB_PASS:curiokeep}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  jackson:
    default-property-inclusion: non_empty

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.rostislav.curiokeep: DEBUG   #while developing
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [rid=%X{rid}] %logger{36} - %msg%n"


curiokeep:
  modules:
    classpath: "classpath*:modules/*.xml"
    schema: "classpath:schema/module-schema-v1.xsd"
    external-dir: ""   # later: /data/modules (mounted in docker)
  assets:
    dir: ./data/assets
  providers:
    credentials:
      encryption:
        password: changeme
        salt: 5f4dcc3b5aa765d6
